name: HostApp
options:
  bundleIdPrefix: com.soundwave
  deploymentTarget:
    iOS: "14.0"
targets:
  HostApp:
    platform: iOS
    type: application
    sources:
      - path: Sources
      - path: Resources
        type: folder
    settings:
      base:
        SWIFT_VERSION: 5.0
        PRODUCT_BUNDLE_IDENTIFIER: com.soundwave.host
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: "SoundWave Host"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    scheme:
      gatherCoverageData: false
    dependencies:
      - framework: ../../soundwave_player/ios/core/build/SoundwaveCore.xcframework
